# Generated by Django 5.0.6 on 2024-09-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
