# Generated by Django 5.0.6 on 2024-09-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transactions_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
